name: Manual Hello World

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - feature/4

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Log Hello World
        run: echo "Hello, World!"
